### ISSUE TITLE
Oppdaterings probs

### ISSUE THREAD

**Issue by Haavaoso** [Ecos-platform/vcpkg-registry#1]
Hei,
sliter med og oppdatere threpp Baselinen. Programmet kaster ut dette når jeg reset cash og reloader cmake: 
-- Running vcpkg install
Fetching registry information from https://github.com/Ecos-platform/vcpkg-registry (HEAD)...
Fetching baseline information from https://github.com/Ecos-platform/vcpkg-registry...
Couldn't find baseline in commit `"bc2c610f1613e824b9df81d5bba0ddb4e9161b1e"` from repo https://github.com/Ecos-platform/vcpkg-registry:
error: git failed with exit code: (128).
fatal: path 'versions/baseline.json' exists on disk, but not in 'bc2c610f1613e824b9df81d5bba0ddb4e9161b1e'

-- Running vcpkg install - failed

Prøvd med flere baseline men samme error uansett. Eneste som fungerer er orginal baselinen. Kan du gå igjennom dette i neste time? 
Orginal baseline er 4e6a2ca0635e15000cd0df4835b1936322de7791.

**Comment by markaren** [comment]
Kan du poste `vcpkg-configuration.json` som du bruker?

**Comment by Haavaoso** [comment]
God helg, her er min

**Comment by Haavaoso** [comment]
God helg, her er mon vcpkg-configuration.json
```json
{
  "default-registry": {
    "kind": "git",
    "repository": "https://github.com/Microsoft/vcpkg",
    "baseline": "d558a1b4afd52e2659d7d2b6783cb2eb11add926"
  },
  "registries": [
    {
      "kind": "git",
      "baseline": "bc2c610f1613e824b9df81d5bba0ddb4e9161b1e",
      "repository": "https://github.com/Ecos-platform/vcpkg-registry",
      "packages": [ "threepp" ]
    }
  ]
}
```

**Comment by markaren** [comment]
Ja, problemet er at du bruker en `git-tree` (denne brukes internt av porten) som baseline, mens man skal bruke en git `commit`.
f.eks en av https://github.com/Ecos-platform/vcpkg-registry/commits/main

Bruk gjerne den seneste som du finner fra https://github.com/AIS1002-OOP-V23/threepp/blob/master/tests/threepp_vcpkg_test/vcpkg-configuration.json

**Comment by Haavaoso** [comment]
Aha takker  <3
![skull](https://user-images.githubusercontent.com/123083569/226109292-d25b41fa-68ac-48c9-a3b9-7936f1fd3bd7.gif)
